<a href="https://colab.research.google.com/github/wiemila/ML-courses/blob/main/Deep_Learning_Prerequisites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Arrays vs Pandas lists

In [1]:
import numpy as np

make a list

In [2]:
L=[1,2,3]

make an np array

In [4]:
A = np.array ([1,2,3])

do somthing with each item

In [5]:
for e in L:
  print (e)

1
2
3


In [6]:
for e in A:
  print (e)

1
2
3


the same but now try to append

In [7]:
L.append (4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

the size of a list can change but size of an array is fixed, if you add an item to an array it really creates a new array.
So there is no append for arrays

In [10]:
L+ [5]

[1, 2, 3, 4, 5]

this opperation is contatenate but for an array its broadcasting

In [11]:
A+ np.array([4])

array([5, 6, 7])

it added 4 to each item, in maths it will be an illegal operation because you cannot add two vectors of different sizes

In [13]:
A+ np.array([4,5,6])

array([5, 7, 9])

its intelligent it broadcasts if one item is added to an array and add vectors if they are the same size, if they will be different sizes it gives an error

In [14]:
2*A

array([2, 4, 6])

In [15]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

for array it gives a mathematical operation for list it duplicates a list is like L+L

In [16]:
L2=[]
for e in L:
  L2.append (e+3)

In [17]:
L2

[4, 5, 6, 7]

added 3 to each element of the list

In [18]:
L2 = [e+3for e in L]
L2

[4, 5, 6, 7]

gives the same

In [19]:
L2=[]
for e in L:
  L2.append (e**2)

In [20]:
L2

[1, 4, 9, 16]

each element squared can be done by going through each element with a loop, much easier with an array

In [22]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [23]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

with arrays its easy to make operations on single elements, do not have to enumarate

In [25]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

A list looks like an array but its a generic data structure. Numpy array exists specifically to do math -cannot change size easily

# Dot product

In [27]:
a=np.array([1,2])
b=np.array([3,4])

multiply two arrays element wise and sum the those results together

In [30]:
dot =0
for e, f in zip(a,b):
  dot +=e*f
dot

11

above a zip funciton was used to go through elements one by one but if we have arrays we can use indexing

In [31]:
dot =0
for i in range (len(a)):
  dot+= a[i]* b[i]
dot

11

multiplication

In [32]:
a*b

array([3, 8])

to get a dot product we can sum

In [33]:
np.sum(a*b)

11

In [34]:
(a*b).sum()

11

In [35]:
np.dot(a,b)

11

In [36]:
a.dot(b)

11

In [37]:
a@b

11

many different methods to do the same operation

magnitute of a vector is just square root of a sum of all the elements squared

In [40]:
magVa=np.sqrt(np.sum(a**2))
magVa

2.23606797749979

In [41]:
amag=np.sqrt((a*a).sum())
amag

2.23606797749979

In [42]:
np.linalg.norm(a)

2.23606797749979

pierwsza wersja moja, druga z kursu, trzecia gotowa metoda z algebry liniowej

In [45]:
cosangle=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.9838699100999074

this is a cos of an angle to have an angle we need to do arccos

In [46]:
angle =np. arccos(cosangle)
angle

0.17985349979247847

When programming think about avoiding for loops

#Matrices

2 dimensional arrays are as matrices

there is an actual object numpy.matrix but its not recommended to use, because it must be 2 dimensional and np.array can be any dimensional

if not using numpy how to make a matrix

In [47]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

this is a list of lists, how to access it

In [48]:
L[0]

[1, 2]

row first later column

In [49]:
L[0][1]

2

how to do it using numpy

In [51]:
A = np.array ([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [52]:
A[0][1]

2

can be accessed as a list of lists

In [53]:
A[0,1]

2

select a column

In [54]:
A[:,0]

array([1, 3])

In [55]:
A.T

array([[1, 3],
       [2, 4]])

can be transposed

In [56]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

exp for each element in case of numpy array but with a list it will be the same becaus it will assume its an array

In [57]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

Matrix multiplication

In [60]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

(*)gives element by element multiplication and not a matrix multiplication, for matrix multiplication the inner size must match

In [62]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

doesnt work because the size is wrong

In [63]:
np.linalg.det(A)

-2.0000000000000004

In [64]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

we can check if its correct

In [65]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

the algorithms are not exact so if you dont need to do an inverse do not do it

In [66]:
np.trace(A)

5

In [67]:
np.diag(A)

array([1, 4])

In [68]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

function is overloded if you put on an array you get a vector and if put a vector get an array

the top is a diagonal matrix

eigenvalues and eigenvectors

In [69]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

check if the values are correct

In [71]:
Lam, V = np.linalg.eig(A)

zeroth eigenvalue * zeroth eigenvector = a* the same eingenvector

In [72]:
V[:,0]* Lam[0]==A@ V[:,0]

array([ True, False])

In [73]:
V[:,0]* Lam[0],A@ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

the values look like there are equal but numpy thinks they are not because of numerical precision, computers do not have infinite memory so they do not have infinite precision
To correctly compare whether two arrays are equal numpy all close function should be used

In [74]:
np.allclose(V[:,0]* Lam[0],A@ V[:,0])

True

we can check all the eigenvectors at the same time using matrix notation

In [75]:
np.allclose(V@ np.diag(Lam), A@V)

True