<a href="https://colab.research.google.com/github/wiemila/ML-courses/blob/main/Deep_Learning_Prerequisites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Arrays vs Pandas lists

In [1]:
import numpy as np

make a list

In [2]:
L=[1,2,3]

make an np array

In [4]:
A = np.array ([1,2,3])

do somthing with each item

In [5]:
for e in L:
  print (e)

1
2
3


In [6]:
for e in A:
  print (e)

1
2
3


the same but now try to append

In [7]:
L.append (4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

the size of a list can change but size of an array is fixed, if you add an item to an array it really creates a new array.
So there is no append for arrays

In [10]:
L+ [5]

[1, 2, 3, 4, 5]

this opperation is contatenate but for an array its broadcasting

In [11]:
A+ np.array([4])

array([5, 6, 7])

it added 4 to each item, in maths it will be an illegal operation because you cannot add two vectors of different sizes

In [13]:
A+ np.array([4,5,6])

array([5, 7, 9])

its intelligent it broadcasts if one item is added to an array and add vectors if they are the same size, if they will be different sizes it gives an error

In [14]:
2*A

array([2, 4, 6])

In [15]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

for array it gives a mathematical operation for list it duplicates a list is like L+L

In [16]:
L2=[]
for e in L:
  L2.append (e+3)

In [17]:
L2

[4, 5, 6, 7]

added 3 to each element of the list

In [18]:
L2 = [e+3for e in L]
L2

[4, 5, 6, 7]

gives the same

In [19]:
L2=[]
for e in L:
  L2.append (e**2)

In [20]:
L2

[1, 4, 9, 16]

each element squared can be done by going through each element with a loop, much easier with an array

In [22]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [23]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

with arrays its easy to make operations on single elements, do not have to enumarate

In [25]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

A list looks like an array but its a generic data structure. Numpy array exists specifically to do math -cannot change size easily

# Dot product