<a href="https://colab.research.google.com/github/wiemila/ML-courses/blob/main/Lab_1%262_Numpy_Pandas_student_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><img src='https://drive.google.com/uc?id=1_utx_ZGclmCwNttSe40kYA6VHzNocdET' height="60"></center>

AI TECH - Akademia Innowacyjnych Zastosowań Technologii Cyfrowych. Program Operacyjny Polska Cyfrowa na lata 2014-2020
<hr>

<center><img src='https://drive.google.com/uc?id=1BXZ0u3562N_MqCLcekI-Ens77Kk4LpPm'></center>

<center>
Projekt współfinansowany ze środków Unii Europejskiej w ramach Europejskiego Funduszu Rozwoju Regionalnego
Program Operacyjny Polska Cyfrowa na lata 2014-2020,
Oś Priorytetowa nr 3 "Cyfrowe kompetencje społeczeństwa" Działanie  nr 3.2 "Innowacyjne rozwiązania na rzecz aktywizacji cyfrowej"
Tytuł projektu:  „Akademia Innowacyjnych Zastosowań Technologii Cyfrowych (AI Tech)”
    </center>

# Statistical machine learning - Notebook 1

**Author: Maciej Bartczak**



# Bootcamp - introduction to machine learning: NumPy & Pandas


## What is NumPy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, basic linear algebra, statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, **such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences**.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.



from: https://numpy.org/doc/stable/user/whatisnumpy.html

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Array creation

There are multiple ways to create an array, try examples below.

### From nested lists

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [3]:
array_2d = np.array(
  [
    [1,  2,  3,  4,  5 ],
    [6,  7,  8,  9,  10],
    [11, 12, 13, 14, 15]
  ]
)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
array_3d = np.array(
  [
    [
      [1,  2,  3,  4,  5 ],
      [6,  7,  8,  9,  10],
      [11, 12, 13, 14, 15],
    ],
    [
      [16, 17, 18, 19, 20],
      [21, 22, 23, 24, 25],
      [26, 27, 28, 29, 30],
    ]
  ]
)
array_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

### Using zeros / ones / full



In [5]:
shape = (2, 3)

np.zeros(shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
fill_value = 42
np.full(shape, fill_value)

array([[42, 42, 42],
       [42, 42, 42]])

### Using zeros_like / ones_like / full_like

In [8]:
np.zeros_like(array_2d)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones_like(array_2d)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
fill_value = 42
np.full_like(array_2d, fill_value)

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

### Using arange / linspace (1D arrays only)

which are used to fill an array with values from the interval $[low, high]$ with specific step or number of points.

In [13]:
start = 0
stop  = 1
step  = 0.1

np.arange(start, stop, step)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
np.arange(start, stop + 1e-4, step)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
n_steps = int((stop-start)/step) + 1
np.linspace(start, stop, n_steps)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Using identity / diag (2D arrays only)
 to create identity or diagonal (with optional offset) matrices.

In [16]:
n = 4
np.identity(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
offset = 1
np.diag([1, 2, 3], offset)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### Using meshgrid
For 1D arrays X_1, ..., X_n meshgrid behavior is specified as follows

```
G_1, ..., G_n = np.meshgrid(X_1, ..., X_n, indexing='ij')
G_j[i_1, i_2, ..., i_n] = X_j[i_j]

G_1, ..., G_n = np.meshgrid(X_1, ..., X_n, indexing='xy')  # default indexing
G_j[i_2, i_1, i_3, ..., i_n] = X_j[i_j]
```

what facilitates creating coordinate grids,




In [19]:
x = np.array([1, 2, 3], dtype=int)
y = np.array([4, 5, 6, 7], dtype=int)

x_grid, y_grid = np.meshgrid(x, y, indexing='ij')

such as:

In [20]:
x_grid

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [21]:
y_grid

array([[4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [22]:
x_grid.shape == y_grid.shape == (len(x), len(y))

True

### Using tile & repeat
to create an array filled with "repeating pattern".

In [23]:
array = np.array([0,1,2])

In [24]:
np.tile(array, 2)

array([0, 1, 2, 0, 1, 2])

In [25]:
np.tile(array, (2, 1))

array([[0, 1, 2],
       [0, 1, 2]])

In [26]:
np.repeat(array, 2)

array([0, 0, 1, 1, 2, 2])

In [27]:
np.repeat(array, 2, axis=0)

array([0, 0, 1, 1, 2, 2])

In [28]:
np.repeat(array.reshape(1, -1), 2, axis=0)

array([[0, 1, 2],
       [0, 1, 2]])

In [29]:
np.repeat(array.reshape(1, -1), 2, axis=1)

array([[0, 0, 1, 1, 2, 2]])

## NumPy dtypes

Full list of NumPy dtypes is available here: https://numpy.org/doc/stable/user/basics.types.html

Among which there are 5 basic numerical types representing booleans (bool), integers (int), unsigned integers (uint) floating point (float) and complex.

Data-types can be used as arguments to the dtype keyword that many numpy functions or methods accept, in particular array creation routines.

See examples below.

In [30]:
np.array([1, 2, 3, 4, 5], dtype=int)

array([1, 2, 3, 4, 5])

In [31]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [32]:
np.array([1, 2, 3, 4, 5], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

Types can be cast as follows

In [33]:
float_array   = np.array([1, 2, 3, 4, 5], dtype=float)
complex_array = float_array.astype(complex)

float_array, float_array.dtype

(array([1., 2., 3., 4., 5.]), dtype('float64'))

In [34]:
complex_array, complex_array.dtype

(array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]), dtype('complex128'))

## Saving / loading data

### Using savetxt / loadtxt

to process a single 1D/2D array in human readable format. File created with `savetxt` can be easily accessed with a text editor

In [52]:
data = np.array(
  [
    [1, 2],
    [3, 4],
  ]
)

np.savetxt('data.txt', data)
!cat data.txt

1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00


as well as seamlessly loaded back with `loadtxt`.


In [53]:
np.loadtxt('data.txt')

array([[1., 2.],
       [3., 4.]])

File format can be specified, see https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html for reference

In [54]:
np.savetxt('data.txt', data, fmt='%.2f')
!cat data.txt

1.00 2.00
3.00 4.00


In [55]:
np.savetxt('data.txt', data, fmt='%d')
!cat data.txt

1 2
3 4


Nevertheless information regarding dtype is not preserved.

In [56]:
np.loadtxt('data.txt')

array([[1., 2.],
       [3., 4.]])

In [57]:
np.loadtxt('data.txt', dtype=int)

array([[1, 2],
       [3, 4]])

`savetxt` method can be used to save an array in csv format, we only need to specify the proper delimiter

In [58]:
np.savetxt('data.csv', data, delimiter=',', fmt='%.2f')
!cat data.csv

1.00,2.00
3.00,4.00


as well as loaded back

In [59]:
np.loadtxt('data.csv', delimiter=',')

array([[1., 2.],
       [3., 4.]])

### Using save / load
to process an arbitrary array in binary format. Unfortunately the resulting file is not human readable. On the other hand these methods can handle array of arbitrary shape and preserve the underlying dtype.

In [60]:
data = np.array(
  [
    [
      [1, 2],
      [3, 4],
    ]
  ]
)

np.save('data.npy', data)

!cat data.npy

�NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (1, 2, 2), }                                                       


In [61]:
np.load('data.npy')

array([[[1, 2],
        [3, 4]]])

In [62]:
np.load('data.npy').dtype == data.dtype

True

### Using savez / load

to process **multiple** arbitrary arrays in binary format. The result of the load operation is an object of dictionary-like structure.

In [63]:
array_1 = np.array([1, 2, 3], dtype=int)
array_2 = np.array([[4, 5, 6]], dtype=float)
array_3 = np.array([[[7, 8, 9]]], dtype=complex)

np.savez('data.npz', array_1, array_2, some_name=array_3)
loaded_data = np.load('data.npz')
loaded_data.files

['some_name', 'arr_0', 'arr_1']

In [64]:
loaded_data['arr_0']

array([1, 2, 3])

In [65]:
loaded_data['arr_1']

array([[4., 5., 6.]])

In [66]:
loaded_data['some_name']

array([[[7.+0.j, 8.+0.j, 9.+0.j]]])

### Using savez_compressed / load
to process multiple arbitrary arrays in binary format with compression. It behaves just as savez but the resulting file is also compressed, what save space on the disk.



In [67]:
shape = (1000, 1000)
data = np.ones(shape)
np.savez('data_uncompressed.npz', data)
np.savez_compressed('data_compressed.npz', data)

We can compare the filesizes with `ls` command.

In [68]:
!ls data_*compressed.npz -lh

-rw-r--r-- 1 root root  12K Nov  5 15:57 data_compressed.npz
-rw-r--r-- 1 root root 7.7M Nov  5 15:57 data_uncompressed.npz


## Shape manipulation
It is possible to change the structure of data in the array. See examples below.

#### Reshape

In [69]:
data = np.arange(0, 12, 1, dtype = int)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
data.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
data.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
data_reshaped = data.reshape(2, 3, 2)
data_reshaped

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [73]:
shape = data_reshaped.shape
shape

(2, 3, 2)

#### Inferring **one** dimension while usigng reshape method

In [74]:
data.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [75]:
data.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [76]:
data.reshape(3, 2, -1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

#### Flatten

In [77]:
data_reshaped.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Adding / deleting dummy dimensions
Facilites vectorized arithmetic with conjunction with broadcasting mechanism (explained later)

In [78]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
data.shape

(12,)

In [80]:
data_expanded1 = np.expand_dims(data, 0)
data_expanded1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [81]:
data_expanded1.shape

(1, 12)

In [82]:
data_expanded2 = np.expand_dims(data, 1)
data_expanded2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [83]:
data_expanded2.shape

(12, 1)

In [84]:
data_expanded3 = np.expand_dims(data_expanded1, 2)
data_expanded3

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

In [85]:
data_expanded3.shape

(1, 12, 1)

In [86]:
data_squeezed = data_expanded3.squeeze()
data_squeezed

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
data_squeezed.shape

(12,)

#### Transposing

For 2D arrays it behaves just as expected (performs matrix transpose).

In [88]:
data = np.arange(0, 4, 1).reshape(2, 2)
data

array([[0, 1],
       [2, 3]])

In [89]:
data.transpose()

array([[0, 2],
       [1, 3]])

For higher dimensional arrays its best visualized via observing how the shape changes.

In [90]:
shape = (1, 2, 3, 4)
data = np.ones(shape)
data.shape

(1, 2, 3, 4)

The default behavior is to flip dimensions.

In [91]:
data.transpose().shape

(4, 3, 2, 1)

However other permutations of dimensions might be specified.

In [92]:
dimensions_permutation = [1, 0, 3, 2]
data.transpose(dimensions_permutation).shape

(2, 1, 4, 3)

`.T` is a shortand for `.transpose()`

In [93]:
data.T.shape

(4, 3, 2, 1)

## Concatenation & stacking
The following methods are used to merge multiple arrays (with compatible shapes) into one array.

### concatenate
used to join a sequence of arrays along an **existing** axis.

In [94]:
shape = (4,)
array_1 = np.full(shape, 1)
array_2 = np.full(shape, 2)

array_1, array_2

(array([1, 1, 1, 1]), array([2, 2, 2, 2]))

In [95]:
np.concatenate([array_1, array_2, array_1])

array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1])

In [97]:
array_1 = array_1.reshape(1, -1)
array_2 = array_2.reshape(1, -1)

array_1, array_2

(array([[1, 1, 1, 1]]), array([[2, 2, 2, 2]]))

The default axis to join on is 0

In [98]:
np.concatenate([array_1, array_2, array_1])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1]])

But it can be changed

In [99]:
np.concatenate([array_1, array_2, array_1], axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1]])

### stack

used to stack a sequence of arrays along a **new** axis.

In [100]:
shape = (4,)
array_1 = np.full(shape, 1)
array_2 = np.full(shape, 2)

array_1, array_2

(array([1, 1, 1, 1]), array([2, 2, 2, 2]))

In [101]:
np.stack([array_1, array_2, array_1])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1]])

In [102]:
np.stack([array_1, array_2, array_1], axis=1)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])


### hstack, vstack and dstack
stand for horizontal, vertical and depthwise stacking

In [103]:
np.hstack([array_1, array_2, array_1])

array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1])

In [104]:
np.vstack([array_1, array_2, array_1])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [1, 1, 1, 1]])

In [105]:
np.dstack([array_1, array_2, array_1])

array([[[1, 2, 1],
        [1, 2, 1],
        [1, 2, 1],
        [1, 2, 1]]])

## Mathematical operations
As stated before

> NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

Let us observe some examples.



In [113]:
x = np.arange(0, 3, 1)
y = np.arange(3, 6, 1)

x, y

(array([0, 1, 2]), array([3, 4, 5]))

#### Elementwise

Basic mathematical operations will be applied to the arrays elementwise.

In [114]:
2 * x

array([0, 2, 4])

In [115]:
x * 2

array([0, 2, 4])

In [116]:
np.sin(x)

array([0.        , 0.84147098, 0.90929743])

In [117]:
x**2

array([0, 1, 4])

The same applies to the binary (taking two arguments) operators and arrays of the same shape.

In [118]:
x + y

array([3, 5, 7])

In [119]:
x * y

array([ 0,  4, 10])

In [120]:
x / y

array([0.  , 0.25, 0.4 ])

In [121]:
y ** x

array([ 1,  4, 25])

#### Broadcasting

When arrays have different shapes the broadcasting mechanism comes into play.

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

- they are equal, or
- one of them is 1

If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

from: https://numpy.org/devdocs/user/basics.broadcasting.html

In [124]:
x_shape = (2, 4)
y_shape = (2, 1)

x = np.ones(x_shape)
y = np.ones(y_shape)

(x + y).shape

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [126]:
x_shape =    (2, 4)
y_shape = (3, 1, 1)

x = np.ones(x_shape)
y = np.ones(y_shape)

(x + y).shape

(3, 2, 4)

In [127]:
x_shape = (   1, 4)
y_shape = (3, 2, 1)

x = np.ones(x_shape)
y = np.ones(y_shape)

(x + y).shape

(3, 2, 4)

### Matrix / tensor operations
NumPy package wouldn't be complete without means to manipulate arrays other than elementwise operations, such as most common linear algebra functionalities. See the examples below.

#### Matrix multiplication

can be performed with `matmul` method

In [128]:
a = np.eye(3)
a[2,2] = 2
b = np.arange(0, 3, 1).reshape(3, 1)

a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

In [129]:
b

array([[0],
       [1],
       [2]])

In [130]:
np.matmul(a, b)

array([[0.],
       [1.],
       [4.]])

or `@` operand

In [131]:
a @ b

array([[0.],
       [1.],
       [4.]])

Be mindfull of its varying behaviour for different input shapes

- If both arguments are 2-D they are multiplied like conventional matrices.
- If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.
- If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
- If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

from: https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

#### Dot product

can be performed using `dot` method.

In [132]:
x = np.arange(0, 3, 1)
y = np.arange(3, 6, 1)

x, y

(array([0, 1, 2]), array([3, 4, 5]))

In [133]:
np.dot(x, y)

np.int64(14)

Be mindfull of its varying behaviour for different input shapes

- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

- If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

- If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

- If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

  ```
  dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
  ```

from: https://numpy.org/doc/stable/reference/generated/numpy.dot.html


#### Einstein summation convention
Einstein summation convention provide a concise way of expressing multilinear operations. You can look it up here https://mathworld.wolfram.com/EinsteinSummation.html and its NumPy specification here https://numpy.org/doc/stable/reference/generated/numpy.einsum.html.

Take a look a the following ilustrative examples.


In [134]:
data = np.tri(3)
data

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [135]:
np.einsum('ij->ji', data)  # transpose

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [136]:
np.einsum('ij->i', data)  # row sum

array([1., 2., 3.])

In [137]:
np.einsum('ij->j', data)  # column sum

array([3., 2., 1.])

In [138]:
np.einsum('ii->i', data)  # diagonal

array([1., 1., 1.])

In [139]:
vector = np.ones(3)
vector

array([1., 1., 1.])

In [140]:
np.einsum('ij,j->i', data, vector)  # matrix multiplication (matrix x vector)

array([1., 2., 3.])

In [141]:
np.einsum('ij,jk->ik', data, vector.reshape(3, 1))  # matrix multiplication (matrix x matrix)

array([[1.],
       [2.],
       [3.]])

## Other operations

### Aggregations: mean / var
Very often we are required to calculate some aggregations with respect to specific dimensions of an array, such as mean or variance.

In [142]:
data = np.arange(0, 20, 1).reshape(4, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

By default the whole array is aggregated

In [143]:
data.mean()

np.float64(9.5)

But aggregations can also be applied axiswise

In [144]:
data.mean(axis=0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [145]:
data.mean(axis=1)

array([ 2.,  7., 12., 17.])

In [146]:
data.var(axis=0)

array([31.25, 31.25, 31.25, 31.25, 31.25])

In [147]:
data.var(axis=1)

array([2., 2., 2., 2.])

### Aggregation: quantiles

Many more aggregations are possible, e.g. determining data quantiles.

In [148]:
data = np.linspace(1, 2, 101)

np.quantile(data, 0.3)

np.float64(1.3)

In [149]:
np.quantile(data, [0.3, 0.6])

array([1.3, 1.6])

### Sorting
Arrays can be sorted. By default sorting is performed with respect to the last dimension

In [150]:
data = np.array([
  [1, 4, 2, 8, 5],
  [2, 3, 1, 9, 6],
  [8, 2, 3, 7, 4],
])

np.sort(data)

array([[1, 2, 4, 5, 8],
       [1, 2, 3, 6, 9],
       [2, 3, 4, 7, 8]])

but sorting dimension can be explicitly specified.

In [151]:
np.sort(data, axis=0)

array([[1, 2, 1, 7, 4],
       [2, 3, 2, 8, 5],
       [8, 4, 3, 9, 6]])

In [152]:
np.sort(data, axis=1)

array([[1, 2, 4, 5, 8],
       [1, 2, 3, 6, 9],
       [2, 3, 4, 7, 8]])

You can also get the "sorting permutations" that can be used in conjunction with advanced indexing (introduced below).

In [154]:
np.argsort(data, axis=0)

array([[0, 2, 1, 2, 2],
       [1, 1, 0, 0, 0],
       [2, 0, 2, 1, 1]])

In [155]:
np.argsort(data, axis=1)

array([[0, 2, 1, 4, 3],
       [2, 0, 1, 4, 3],
       [1, 2, 4, 3, 0]])

## Indexing

Allows selecting items and subarrays. It can be also used to modify fragments of an array.

### Basic indexing

In [156]:
data = np.arange(0, 16, 1)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
data[10]

np.int64(10)

In [158]:
data[-2]

np.int64(14)

In [159]:
data[:5]

array([0, 1, 2, 3, 4])

In [160]:
data[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [161]:
data[-3:]

array([13, 14, 15])

It is also possible in higher dimensional setting


In [162]:
data = data.reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [163]:
data[1, 1]

np.int64(5)

In [164]:
data[1, :]

array([4, 5, 6, 7])

One does not need to specify trailing colons `:`

In [165]:
data[:-2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Note how the column selection is achieved. In this case `:` can't be ommited.

In [166]:
data[:, -2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

One group of subsequent colons `:` can be replaced with `...`

In [167]:
data_reshaped = data.reshape(4, 2, 2)
data_reshaped

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [168]:
data_reshaped[..., 0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

Note the difference

In [169]:
data_reshaped[:, 0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

### View & copies

Basic indexing routines presented above return views of the data in the underlying arrays. When the underlying array is modified the changes are reflected in the view.

In [170]:
data = np.arange(0, 16, 1).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
view = data[:, 3]
view

array([ 3,  7, 11, 15])

In [172]:
data *= 2
data

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [173]:
view

array([ 6, 14, 22, 30])

To "detach" view from the underlying array use `copy` method

In [174]:
view_copy = view.copy()
data *= 2
view, view_copy

(array([12, 28, 44, 60]), array([ 6, 14, 22, 30]))

Views are only possible when selecting with slices, then it's a matter of rememebering offset and stride only.

You can read more about this here: https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

### Advanced indexing

it is also possible to index with integer or boolean arrays

In [175]:
data = np.arange(0, 16, 1).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

We can select specific rows

In [176]:
data[[0, 3]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

and columns.

In [177]:
data[:, [0, 3]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

Seleceting both together is a little more complicated

In [178]:
rows = [
 [0, 0],
 [3, 3]
]
columns = [
 [0, 3],
 [0, 3]
]
data[rows, columns]

array([[ 0,  3],
       [12, 15]])

Use indices shape to control the output shape.

In [179]:
rows = [0, 0, 3, 3]
columns = [0, 3, 0, 3]
data[rows, columns]

array([ 0,  3, 12, 15])

Boolean arrays can be used as well, though they work somewhat differently.

In [180]:
index = (data % 3 == 0)
index

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [181]:
data[index]

array([ 0,  3,  6,  9, 12, 15])

Its most common use case is to update array entries based on some condition.

In [182]:
data[index] = -1
data

array([[-1,  1,  2, -1],
       [ 4,  5, -1,  7],
       [ 8, -1, 10, 11],
       [-1, 13, 14, -1]])

Detailed bahavior of indexing with boolean arrays is described here: https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing

# NumPy Exercises

### Exercise: multiplication table
Create "{0, ..., 10} x {0, ..., 10} multiplication table" using only
- `meshgrid` method,
- multiplication of 1D arrays, dummy dimensions and broadcasting mechanism.

In [185]:
### YOUR CODE BEGINS HERE ###
x = np.arange(11)
X, Y = np.meshgrid(x, x)
table_meshgrid = X * Y
print("Using meshgrid:\n", table_meshgrid)
### YOUR CODE ENDS HERE ###

Using meshgrid:
 [[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   2   3   4   5   6   7   8   9  10]
 [  0   2   4   6   8  10  12  14  16  18  20]
 [  0   3   6   9  12  15  18  21  24  27  30]
 [  0   4   8  12  16  20  24  28  32  36  40]
 [  0   5  10  15  20  25  30  35  40  45  50]
 [  0   6  12  18  24  30  36  42  48  54  60]
 [  0   7  14  21  28  35  42  49  56  63  70]
 [  0   8  16  24  32  40  48  56  64  72  80]
 [  0   9  18  27  36  45  54  63  72  81  90]
 [  0  10  20  30  40  50  60  70  80  90 100]]


In [186]:

x = np.arange(11)
table_outer = np.outer(x, x)
print("\nUsing outer product (1D array multiplication):\n", table_outer)


Using outer product (1D array multiplication):
 [[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   2   3   4   5   6   7   8   9  10]
 [  0   2   4   6   8  10  12  14  16  18  20]
 [  0   3   6   9  12  15  18  21  24  27  30]
 [  0   4   8  12  16  20  24  28  32  36  40]
 [  0   5  10  15  20  25  30  35  40  45  50]
 [  0   6  12  18  24  30  36  42  48  54  60]
 [  0   7  14  21  28  35  42  49  56  63  70]
 [  0   8  16  24  32  40  48  56  64  72  80]
 [  0   9  18  27  36  45  54  63  72  81  90]
 [  0  10  20  30  40  50  60  70  80  90 100]]


In [187]:
x = np.arange(11)
table_broadcast = x[:, None] * x[None, :]
print("\nUsing broadcasting with dummy dimensions:\n", table_broadcast)


Using broadcasting with dummy dimensions:
 [[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   2   3   4   5   6   7   8   9  10]
 [  0   2   4   6   8  10  12  14  16  18  20]
 [  0   3   6   9  12  15  18  21  24  27  30]
 [  0   4   8  12  16  20  24  28  32  36  40]
 [  0   5  10  15  20  25  30  35  40  45  50]
 [  0   6  12  18  24  30  36  42  48  54  60]
 [  0   7  14  21  28  35  42  49  56  63  70]
 [  0   8  16  24  32  40  48  56  64  72  80]
 [  0   9  18  27  36  45  54  63  72  81  90]
 [  0  10  20  30  40  50  60  70  80  90 100]]


### Exercise: speed comparison
In this exercise we will measure the speed improvements due to NumPy implementation.

In [ ]:
length = 10000
a = b = np.arange(length)

Write the code to calculate dotproduct of arrays `a` and `b` using only native Python funcions. Use `timeit` magic to time the execution.

In [ ]:
%%timeit

### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

Now compare the execution time with `np.dot`.

In [ ]:
### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

### Exercise: vector operations
Calculate
$$ \int_0^1 \sin(a\cdot2\pi x)\sin(b\cdot 2\pi x)dx $$
for
- $a=b=1$,
- $a=1$ and $b=2$,

using discrete approximation of an integral and following NumPy functions: `linspace, sin, mean`. Do not use `vectorize`.


In [ ]:
# Case a = b = 1
### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

print(answer.round(4))
assert np.isclose(answer, 0.5)

In [ ]:
np.linspace(0, 1, 10, endpoint=False)
np.linspace(0, 1, 11)[:-1]

In [ ]:
# Case a = 1, b = 2
### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###
print(answer.round(4))
assert np.isclose(answer, 0)

### Exercise: vector operations ctd.

Let $a_j = j$. Calculate in a similar fashion matrix $(b_{ij})_{i,j=0, ..., 4}$, where
$$ b_{ij} = \int_0^1 \sin(a_i\cdot2\pi x)\sin(a_j\cdot 2\pi x)dx. $$

Try to structure your code in such a way that it would accept an arbitrary array `a`. Do not use `vectorize`.

In [ ]:
a = np.arange(5)

### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

print(answer.round(2))
assert np.isclose(answer, np.diag([0, 0.5, 0.5, 0.5, 0.5])).all()

### Exercise: subarrays

Let us sample $n=100 000$ standard normal random variables. Calculate mean of values greater than zero.

In [ ]:
np.random.seed(0)

n = 100000
sample = np.random.randn(n)

### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

assert np.isclose(answer, np.sqrt(2/np.pi), rtol=0.01)

### Exercise: subarrays ctd.
Let us sample an array of random integers.
1. Select columns for which sum of its values gives remainder = 1 when divided by 3.
2. Change entries in that columns to ones.
3. Calculate sum of all entries.

In [ ]:
np.random.seed(0)
sample = np.random.randint(0, 3, size=(10, 10))

### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

assert answer == 88


### Exercise: matrix multiplication & merging arrays

In this exercies we will approximate operator norm of some matrices.

1. Create an an array of $n=1000$ vectors $v\in\mathbb{R}^2$ "evenly spaced" on the unit circle.
2. Combine given three matrices into one array.
3. Use **one** matrix multiplication operation with these arrays to obtain matrix products of all the vectors with all the matrices.
4. For each vector calculate its (euclidean) length.
5. Take maximum with respect to each matrix.
6. You should obtain three values representing approximations of operator norm of provided matrices.


In [ ]:
matrix_1 = np.array([
  [1, 0],
  [0, 1]
])

matrix_2 = np.array([
  [1, 1],
  [1, 1]
])

matrix_3 = np.array([
  [1, 1],
  [0, 1]
])

### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

print(answer.round(4))
assert np.isclose(answer, [1, 2, (1+np.sqrt(5))/2]).all()

## Other NumPy functionalities
NumPy package implements plethora of mathematical functionalities, not covered in this tutorial. NumPy User guide and API Reference are great starting point to discover those functionalities:
- https://numpy.org/doc/stable/user/
- https://numpy.org/doc/stable/reference/


# What is pandas?

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

It is meant for manipulating datasets in tabular format, that is 2D arrays with rows representing observations and columns representing variables, the so called **DataFrames**.

from: https://pandas.pydata.org/

### Creating dataframes

In the most basic form you just specify 2D array of values

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.arange(0, 16, 1).reshape(4, 4)
)

df

It is possible to additionally specify columns and index labels

In [ ]:
df = pd.DataFrame(
    np.arange(0, 16, 1).reshape(4, 4),
    columns = ['column_1', 'column_2', 'column_3', 'column_4'],
    index   = ['a', 'b', 'c', 'd']
)

df

as well as type of entries

In [ ]:
df = pd.DataFrame(
    np.arange(0, 16, 1).reshape(4, 4),
    columns = ['column_1', 'column_2', 'column_3', 'column_4'],
    index   = ['a', 'b', 'c', 'd'],
    dtype   = float
)

df

In [ ]:
df.astype(int)

It can be done in an alternative manner

In [ ]:
df = pd.DataFrame(
    {
      'column_1': [0,  4,  8, 12],
      'column_2': [1,  5,  9, 13],
      'column_3': [2,  6, 10, 14],
      'column_4': [3,  7, 11, 15]
    },
    index   = ['a', 'b', 'c', 'd']
)

df

It is worth mentioning that the underlying data can be accesed under `values` attribute

In [ ]:
df.values

What's important Pandas DataFrames can handle entries of different type. In the most common situation different columns will have different types.

In [ ]:
df = pd.DataFrame(
    {
      'integers': [0,   1,   2,  3],
      'floats':   [1.0, 2.0, 3,  4],
      'booleans': [True, False, True, False],
      'arbitrary objects':  [0, 1.0, 'abc', False]
    }
)

df

In [ ]:
df.dtypes

Another available creation methods are listed below
- `pd.DataFrame.from_dict`
- `pd.DataFrame.from_records`

You can read about them here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

### Loading data
Let us peek into the CSV file conveniently provided in the Google Colab runtime

In [ ]:
!head './sample_data/california_housing_train.csv'

*and* load it using `pd.read_csv` method.

In [ ]:
pd.read_csv('./sample_data/california_housing_train.csv')

In Pandas it is also possible to load JSON files.

In [ ]:
!head './sample_data/anscombe.json'

In [ ]:
pd.read_json('./sample_data/anscombe.json')

## Other I/O functionalities
They are listed here https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html and are suitable for: XML, HDF, Feather, Parquet files as well as for interaction with various databases and much more.

## Handling missing data and duplicates

In the real world it's often the case that there are missing or duplicate values in the dataset. They can be easily delt with in Pandas.

In [ ]:
df = pd.DataFrame([
  [0,       1     ],
  [2,       0     ],
  [2,       np.nan],
  [np.nan,  np.nan]
])

df

Incomplete observations can be filtered out.

In [ ]:
df.dropna()

In [ ]:
df.dropna(how='all')

It is also possible to "fill the gaps".

In [ ]:
df.fillna(0)

In [ ]:
df.fillna(0).drop_duplicates()

In [ ]:
df.fillna({0: 0, 1: 1})

## Data access

Let us observe how we can access and manipulate DataFrame structure.

In [ ]:
df = pd.read_csv('./sample_data/california_housing_train.csv')
df

### describe & info
Once the dataframe is loaded `describe` and `info`methods provide an easy way to obtain a high level view of the underlying data.

In [ ]:
df.describe()

In [ ]:
df.info()

### head & tail
we can use these methods to look at the first and last entries

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.head(8)

### rename
can be used to rename column labels.

In [ ]:
df.rename(columns={'longitude': 'lon', 'latitude': 'lat'})

### Accessing a subset of data

To select multiple columns specify list of labels within square brackets.

In [ ]:
df[['longitude', 'latitude']]

Single column can be retrieved by specifying its name within square brackets. Note that this will yield a `Series` object which behaves a little different than DataFrames, but in general is a representation of single varaible values.

In [ ]:
df['longitude']

If column name does not contain spaces and other special character it can accesed as an attribute.

In [ ]:
df.longitude

Subset of a DataFrame can be selected using `loc` attribute. You need to specify index and column labels. Note that it supports slicing with respect to column names. Also, as [documentation](https://pandas.pydata.org/pandas-docs/version/0.15.2/indexing.html#different-choices-for-indexing) says *note that contrary to usual python slices, both the start and the stop are included!*.

In [ ]:
df.loc[5:10, 'population': 'median_house_value']

It also possible to select data with slices correspong to indices and columns **positions** (as in NumPy).

In [ ]:
df.iloc[5:10, -4:]

Boolean arrays (including boolean `Series` object) can be used as well.

In [ ]:
index = df.median_house_value < 25000
index

In [ ]:
df.loc[index, 'median_house_value']

It is also possible to do

In [ ]:
df[index]

## Merging dataframes
can be used to merge multiple arrays into one.


In [ ]:
df_1 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['a', 'b', 'c'], index=[0, 1, 2])
df_2 = pd.DataFrame(np.arange(9).reshape(3, 3), columns=['b', 'c', 'd'], index=[1, 2, 3])

In [ ]:
df_1

In [ ]:
df_2

There are to basic methods for merging dataframes. The first one is `append` that concatenates dataframes along the index.

In [ ]:
df_1 = pd.concat([df_1, df_2])

The second one is join that concatenates dataframes along the columns.

In [ ]:
df_1.join(df_2, how='outer', lsuffix='_left', rsuffix='_right')

These two methods are special cases of more general function `concat` that allows more advanced oprations. There is also `merge` method which makes use of database-like joins.

All of these methods are described and explained here: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

## Operations on dataframes
Pandas can be used to perfrom mathematical and other operations on the underlying data.

### Elementwise operations
The most common use case is to create a new column being a result of some operation on existing columns.

In [ ]:
people_per_household = df.population / df.households
people_per_household

In [ ]:
df['people_per_household'] = people_per_household
df

More general function can be applied with use of `apply` method

In [ ]:
def func(row):
  if row.latitude > 0:
    ns_hemisphere = 'N'
  else:
    ns_hemisphere = 'S'

  if row.longitude > 0:
    ew_hemisphere = 'E'
  else:
    ew_hemisphere = 'W'

  gps_label = f"{abs(row.latitude)} {ns_hemisphere}, {abs(row.longitude)} {ew_hemisphere}"

  return gps_label

df.apply(func, axis=1).head()

### GroupBy
can be used to split a dataframe into multiple based on some condition/values

In [ ]:
values = df.median_house_value.round(-4)
values


In [ ]:
gb = df.groupby(values)
gb

Groups labels and indices can be accessed under `groups` attribute and themselves with the use of `get_group` method.

In [ ]:
gb.groups

In [ ]:
gb.get_group(10000)

The main use case of the `groupby` functionality is to split dataframe based on some condition, perform some aggregation within groups and then join the results. An example of such an operation is calcualtin mean within each group.

In [ ]:
gb.mean().head()

You can read more about `groupby` funcionality in teh pandas user guide: https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html

## Pandas Exercises

### Pandas exercise: IMDB movies

In this exercise we will look into IMDB Top 1000 movies dataset. We will first load it into a dataframe.


In [ ]:
url = "https://raw.githubusercontent.com/peetck/IMDB-Top1000-Movies/master/IMDB-Movie-Data.csv"
df = pd.read_csv(url)
df

Part 1.

1. How much should movie earn to be among 2% best earning movies?
2. Select movies that earned more than this value.
3. Calculate their mean rating.

In [ ]:
### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

In [ ]:
# Your code in cell(s) above
assert np.isclose(answer, 7.615)

Part 2.
1. Calculate mean metascore and mean revenue per director. (use groupby)
2. Restrict results to the directors that directed more than four movies. (look up `value_counts` method)
3. Sort the results with respect to the metascore and display the rating as a dataframe.
4. Who is the 3rd director it this rating and what is his/her mean revenue?

In [ ]:
### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

In [ ]:
print(f"Mean revenue of {director} is {revenue:.3f}.")
assert np.isclose(revenue, 43.242)

### Pandas exercises: Anscombe's quartet

In this exercise we will look into so called Anscombe's quartet that visualizes pitfalls of some statistics used to describe datasets

![image](https://upload.wikimedia.org/wikipedia/commons/e/ec/Anscombe%27s_quartet_3.svg)

Firstly, let us load the data.

In [ ]:
df = pd.read_json("./sample_data/anscombe.json")
df

For each series calculate its
- mean value of $X$
- mean value of $Y$
- sample variance of $X$
- sample variance of $Y$
- covariance beetwen $X$ and $Y$

and verify whether for each series you get
- mean of $X$ = 9,
- var of $X$ = 11,
- mean of $Y$ = 7.5 +- 0.01,
- var of $Y$ = 4.125 +- 0.01,
- cov of $X$ and $Y$ = 5.50 +- 0.01,

(you can try to make use of `aggregate` function of a `GroupBy` object)

In [ ]:
### YOUR CODE BEGINS HERE ###

### YOUR CODE ENDS HERE ###

<center><img src='https://drive.google.com/uc?id=1BXZ0u3562N_MqCLcekI-Ens77Kk4LpPm'></center>